# Generated by Django 4.2.1 on 2023-06-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('descipcion', models.TextField(null=True, verbose_name='Descripción')),
                ('autor', models.TextField(max_length=100, verbose_name='Autor')),
            ],
        ),
    ]
