# Generated by Django 4.2.1 on 2023-06-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiPrimeraApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
